version: '3.3'

networks:
  etcd_registrator:
    driver: overlay

services:
  etcd:
    image: "quay.io/coreos/etcd:v3.3"
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: "http://$ETCD_IP:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCDCTL_API: "3"
      SERVICE_2379_NAME: "etcd"
    ports:
    - 2379:2379
    - 2380:2380
    - 4001:4001
    networks:
      - etcd_registrator
    deploy:
      placement:
        constraints: [node.role == manager]


  registrator:
    image: gliderlabs/registrator:latest
    # Tell registrator where the etcd HTTP API is and to use 
    # the docker VM's IP
    command: [ -ip, "$ETCD_IP", "etcd://$ETCD_IP:2379/trunk/services" ]
    volumes:
    # So registrator can use the docker API to inspect containers
    - "/var/run/docker.sock:/tmp/docker.sock"
    depends_on:
    - etcd
    networks:
      - etcd_registrator
    deploy:
      placement:
        constraints: [node.role == manager]
